name: publish-github-action

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-action:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Action Metadata
        run: |
          echo "Validating action.yml..."
          if [ ! -f action.yml ]; then
            echo "Error: action.yml not found in the root of the repository."
            exit 1
          fi
          echo "action.yml is valid."

      - name: Ensure Tag Exists
        id: validate_tag
        run: |
          # Extract the tag from the GitHub context
          TAG="${GITHUB_REF#refs/tags/}"
          if [ -z "$TAG" ]; then
            echo "Error: No tag found. Ensure you push a valid tag."
            exit 1
          fi
          echo "Tag found: $TAG"

      - name: Publish Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "${{ github.ref_name }}"
          prerelease: true
