name: validate-devschema-test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 12 30 * *
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Validate Dev Schema Action
        uses: ./.github/actions/validate
        # with:
        #   schema: "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json"
        #   data: ".devcontainer/devcontainer.json"
        #   verbose: true
